//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NogasmChart {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class NogasmChartProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static NogasmChartProperties defaultInstance = ((NogasmChartProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NogasmChartProperties())));
        
        public static NogasmChartProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public uint LinearDurationMin {
            get {
                return ((uint)(this["LinearDurationMin"]));
            }
            set {
                this["LinearDurationMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint LinearDurationMax {
            get {
                return ((uint)(this["LinearDurationMax"]));
            }
            set {
                this["LinearDurationMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LinearPositionMin {
            get {
                return ((double)(this["LinearPositionMin"]));
            }
            set {
                this["LinearPositionMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double LinearPositionMax {
            get {
                return ((double)(this["LinearPositionMax"]));
            }
            set {
                this["LinearPositionMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double LinearSpeedThreshold {
            get {
                return ((double)(this["LinearSpeedThreshold"]));
            }
            set {
                this["LinearSpeedThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double LinearTimeMultiplier {
            get {
                return ((double)(this["LinearTimeMultiplier"]));
            }
            set {
                this["LinearTimeMultiplier"] = value;
            }
        }
    }
}
